#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "driver/gpio.h"
#include "driver/i2c.h"

#define PIN_IR_1        GPIO_NUM_32
#define PIN_IR_2        GPIO_NUM_33

#define I2C_MASTER_SDA  GPIO_NUM_26
#define I2C_MASTER_SCL  GPIO_NUM_25
#define I2C_PORT        I2C_NUM_0
#define I2C_FREQ_HZ     50000

#define APP_USE_I2C_MUX 0
#define APP_DIAG_MUX_ONLY 0
#define APP_CHARACTERIZATION_MODE 0
#define APP_DETECTOR_MODE 0

#define TCA9548A_ADDR   0x70
#define SENSOR_COUNT    1
#define MAGNETOMETER_I2C_ADDR 0x1E

#define ACQ_MAX_SAMPLES 256
#define ACQ_SAMPLE_MS   20

#define CROSSING_POLL_MS          20
#define CROSSING_TIMEOUT_MS       5000
#define CROSSING_CLEAR_MS         200

#define CHAR_WINDOW_MS  1000
#define CHAR_SAMPLE_MS  20

#define DETECTOR_WINDOW_MS          1000
#define DETECTOR_SAMPLE_MS          20
#define DETECTOR_BASELINE_WINDOWS   15
#define DETECTOR_CONSECUTIVE_HITS   3
#define DETECTOR_MIN_THRESHOLD_RAW  180
#define DETECTOR_NOISE_MULTIPLIER   6
#define DETECTOR_NOISE_MARGIN_RAW   40
#define DETECTOR_AUTO_REBASELINE_WINDOWS 20
#define DETECTOR_AUTO_REBASELINE_STABILITY_RAW 45

#define CLASSIFIER_BASELINE_SAMPLES      100
#define CLASSIFIER_BASELINE_SAMPLE_MS    20
#define CLASSIFIER_MIN_THRESHOLD_RAW     180
#define CLASSIFIER_NOISE_MULTIPLIER      6
#define CLASSIFIER_NOISE_MARGIN_RAW      40

#endif
